<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abbruch',
    'Browse' => 'Durchsuchen',
    'Cancel' => 'Abbrechen',
    'Drag & Drop your files or ' => 'Drag & Drop Ihre Dateien oder ',
    'Error during load' => 'Fehler beim Laden',
    'Error during remove' => 'Fehler beim Entfernen',
    'Error during revert' => 'Fehler beim Zurücksetzen',
    'Error during revert.' => 'Fehler beim Zurücksetzen.',
    'Error during upload' => 'Fehler beim Hochladen',
    'Error during upload.' => 'Fehler beim Hochladen.',
    'Field contains invalid files' => 'Feld enthält ungültige Dateien',
    'Loading' => 'Laden',
    'Please, contact your administrator. Error code: {errorCode}' => 'Bitte wenden Sie sich an Ihren Administrator. Fehlercode: {errorCode}',
    'Remove' => 'Entfernen',
    'Retry' => 'Wiederholen',
    'Size not available' => 'Größe nicht verfügbar',
    'Undo' => 'Rückgängig',
    'Upload' => 'Upload',
    'Upload cancelled' => 'Upload abgebrochen',
    'Upload complete' => 'Upload abgeschlossen',
    'Uploading' => 'Hochladen',
    'Waiting for size' => 'Warten auf Größe',
    'tap to cancel' => 'Tippen Sie auf, um abzubrechen',
    'tap to retry' => 'Tippen Sie auf, um es erneut zu versuchen',
    'tap to undo' => 'Tippen Sie auf, um rückgängig zu machen',
];
