<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Afbreken',
    'Browse' => 'Bladeren',
    'Cancel' => 'Annuleren',
    'Drag & Drop your files or ' => 'Sleep uw bestanden of ',
    'Error during load' => 'Fout tijdens laden',
    'Error during remove' => 'Fout tijdens verwijderen',
    'Error during revert' => 'Fout tijdens terugzetten',
    'Error during revert.' => 'Fout tijdens terugzetten.',
    'Error during upload' => 'Fout tijdens uploaden',
    'Error during upload.' => 'Fout tijdens uploaden.',
    'Field contains invalid files' => 'Veld bevat ongeldige bestanden',
    'Loading' => 'Bezig met laden',
    'Please, contact your administrator. Error code: {errorCode}' => 'Neem contact op met uw beheerder. Foutcode: {errorCode}',
    'Remove' => 'Verwijderen',
    'Retry' => 'Opnieuw',
    'Size not available' => 'Maat niet beschikbaar',
    'Undo' => 'Ongedaan maken',
    'Upload' => 'Upload',
    'Upload cancelled' => 'Upload geannuleerd',
    'Upload complete' => 'Upload voltooid',
    'Uploading' => 'Uploaden',
    'Waiting for size' => 'Wachten op maat',
    'tap to cancel' => 'tik om te annuleren',
    'tap to retry' => 'tik om het opnieuw te proberen',
    'tap to undo' => 'tik om ongedaan te maken',
];
