<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => '중단',
    'Browse' => '찾아보기',
    'Cancel' => '취소',
    'Drag & Drop your files or ' => '파일을 드래그 앤 드롭하거나 ',
    'Error during load' => '로드 중 오류',
    'Error during remove' => '제거 중 오류',
    'Error during revert' => '복귀 중 오류',
    'Error during revert.' => '되 돌리는 중 오류가 발생했습니다.',
    'Error during upload' => '업로드 중 오류',
    'Error during upload.' => '업로드 중 오류가 발생했습니다.',
    'Field contains invalid files' => '필드에 유효하지 않은 파일이 있습니다',
    'Loading' => '로딩',
    'Please, contact your administrator. Error code: {errorCode}' => '관리자에게 문의하십시오. 오류 코드 : {errorCode}',
    'Remove' => '제거',
    'Retry' => '재시도',
    'Size not available' => '크기를 사용할 수 없습니다',
    'Undo' => '실행 취소',
    'Upload' => '업로드',
    'Upload cancelled' => '업로드가 취소되었습니다',
    'Upload complete' => '업로드 완료',
    'Uploading' => '업로드',
    'Waiting for size' => '크기를 기다리는 중',
    'tap to cancel' => '취소하려면 탭하세요',
    'tap to retry' => '다시 시도하려면 누르십시오',
    'tap to undo' => '탭하여 실행 취소',
];
