<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Прервать',
    'Browse' => 'Выберите',
    'Cancel' => 'Отмена',
    'Drag & Drop your files or ' => 'Перетащите файлы или ',
    'Error during load' => 'Ошибка при загрузке',
    'Error during remove' => 'Ошибка при удалении',
    'Error during revert' => 'Ошибка при возврате',
    'Error during upload' => 'Ошибка при загрузке',
    'Field contains invalid files' => 'Поле содержит недопустимые файлы',
    'Loading' => 'Загрузка',
    'Please, contact your administrator. Error code: {errorCode}' => 'Пожалуйста, свяжитесь с вашим администратором. Код ошибки: {errorCode}',
    'Remove' => 'Удалить',
    'Retry' => 'Повторить',
    'Size not available' => 'Невозможно определить размер',
    'Undo' => 'Отменить',
    'Upload' => 'Загрузить',
    'Upload cancelled' => 'Загрузка отменена',
    'Upload complete' => 'Загрузка завершена',
    'Uploading' => 'Загружается',
    'Waiting for size' => 'Определяется размер',
    'tap to cancel' => 'нажмите для отмены',
    'tap to retry' => 'нажмите для повтора',
    'tap to undo' => 'нажмите для отмены',
    'Error during revert.' => 'Ошибка при возврате.',
    'Error during upload.' => 'Ошибка при загрузке.',
];
