<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Avbryta',
    'Browse' => 'Bläddra',
    'Cancel' => 'Avbryt',
    'Drag & Drop your files or ' => 'Dra och släpp dina filer eller',
    'Error during load' => 'Fel under last',
    'Error during remove' => 'Fel under borttagning',
    'Error during revert' => 'Fel vid återgång',
    'Error during revert.' => 'Fel vid återgång.',
    'Error during upload' => 'Fel vid uppladdning',
    'Error during upload.' => 'Fel vid uppladdning.',
    'Field contains invalid files' => 'Fältet innehåller ogiltiga filer',
    'Loading' => 'Läser in',
    'Please, contact your administrator. Error code: {errorCode}' => 'Kontakta din administratör. Felkod: {errorCode}',
    'Remove' => 'Avlägsna',
    'Retry' => 'Försök igen',
    'Size not available' => 'Storlek inte tillgänglig',
    'Undo' => 'Ångra',
    'Upload' => 'Ladda upp',
    'Upload cancelled' => 'Uppladdning avbruten',
    'Upload complete' => 'Uppladdningen är klar',
    'Uploading' => 'uppladdning',
    'Waiting for size' => 'Väntar på storlek',
    'tap to cancel' => 'tryck för att avbryta',
    'tap to retry' => 'Klicka för att försöka igen',
    'tap to undo' => 'tryck för att ångra',
];
