<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abortar',
    'Browse' => 'Examinar',
    'Cancel' => 'Cancelar',
    'Drag & Drop your files or ' => 'Arrastra y suelta tus archivos o ',
    'Error during load' => 'Error durante la carga',
    'Error during remove' => 'Error durante la eliminación',
    'Error during revert' => 'Error durante la reversión',
    'Error during revert.' => 'Error durante la reversión.',
    'Error during upload' => 'Error durante la carga',
    'Error during upload.' => 'Error durante la carga.',
    'Field contains invalid files' => 'El campo contiene archivos no válidos',
    'Loading' => 'Cargando',
    'Please, contact your administrator. Error code: {errorCode}' => 'Por favor, contacte a su administrador. Código de error: {errorCode}',
    'Remove' => 'Eliminar',
    'Retry' => 'Reintentar',
    'Size not available' => 'Tamaño no disponible',
    'Undo' => 'Deshacer',
    'Upload' => 'Upload',
    'Upload cancelled' => 'Carga cancelada',
    'Upload complete' => 'Upload complete',
    'Uploading' => 'Uploading',
    'Waiting for size' => 'Esperando talla',
    'tap to cancel' => 'tocar para cancelar',
    'tap to retry' => 'tap to retry',
    'tap to undo' => 'tap to deshacer',
];
