<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'إحباط',
    'Browse' => 'تصفح',
    'Cancel' => 'إلغاء',
    'Drag & Drop your files or ' => 'قم بسحب وإسقاط ملفاتك أو ',
    'Error during load' => 'خطأ أثناء التحميل',
    'Error during remove' => 'خطأ أثناء الإزالة',
    'Error during revert' => 'خطأ أثناء التراجع',
    'Error during revert.' => 'خطأ أثناء العودة.',
    'Error during upload' => 'خطأ أثناء التحميل',
    'Error during upload.' => 'خطأ أثناء التحميل.',
    'Field contains invalid files' => 'يحتوي الحقل على ملفات غير صالحة',
    'Loading' => 'جاري التحميل',
    'Please, contact your administrator. Error code: {errorCode}' => 'من فضلك ، اتصل بالمسؤول. رمز الخطأ: {errorCode}',
    'Remove' => 'إزالة',
    'Retry' => 'إعادة المحاولة',
    'Size not available' => 'الحجم غير متوفر',
    'Undo' => 'تراجع',
    'Upload' => 'تحميل',
    'Upload cancelled' => 'تم إلغاء التحميل',
    'Upload complete' => 'اكتمل التحميل',
    'Uploading' => 'تحميل',
    'Waiting for size' => 'في انتظار الحجم',
    'tap to cancel' => 'انقر لإلغاء',
    'tap to retry' => 'انقر لإعادة المحاولة',
    'tap to undo' => 'انقر للتراجع',
];
