<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Keskeytä',
    'Browse' => 'Selaa',
    'Cancel' => 'Peruuta',
    'Drag & Drop your files or ' => 'Vedä ja pudota tiedostosi tai',
    'Error during load' => 'Virhe latauksen aikana',
    'Error during remove' => 'Virhe poiston aikana',
    'Error during revert' => 'Virhe palautuksen aikana',
    'Error during revert.' => 'Virhe palautuksen aikana.',
    'Error during upload' => 'Virhe lataamisen aikana',
    'Error during upload.' => 'Virhe lataamisen aikana.',
    'Field contains invalid files' => 'Kenttä sisältää virheellisiä tiedostoja',
    'Loading' => 'Lastaus',
    'Please, contact your administrator. Error code: {errorCode}' => 'Ota yhteyttä järjestelmänvalvojaasi. Virhekoodi: {errorCode}',
    'Remove' => 'Poista',
    'Retry' => 'Yritä uudelleen',
    'Size not available' => 'Kokoa ei saatavilla',
    'Undo' => 'Kumoa',
    'Upload' => 'Lataa',
    'Upload cancelled' => 'Lähetetty peruutettu',
    'Upload complete' => 'Lataa valmis',
    'Uploading' => 'Lähetetään',
    'Waiting for size' => 'Odottaa kokoa',
    'tap to cancel' => 'napauta peruuttaaksesi',
    'tap to retry' => 'napauta ja yritä uudelleen',
    'tap to undo' => 'napauta peruuttaaksesi',
];
