<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abort',
    'Browse' => 'Gennemse',
    'Cancel' => 'Cancel',
    'Drag & Drop your files or ' => 'Træk og slip dine filer eller ',
    'Error during load' => 'Fejl under belastning',
    'Error during remove' => 'Fejl under fjernelse',
    'Error during revert' => 'Fejl under tilbagestilling',
    'Error during revert.' => 'Fejl under tilbagestilling.',
    'Error during upload' => 'Fejl under upload',
    'Error during upload.' => 'Fejl under upload.',
    'Field contains invalid files' => 'Felt indeholder ugyldige filer',
    'Loading' => 'Loading',
    'Please, contact your administrator. Error code: {errorCode}' => 'Kontakt venligst din administrator. Fejlkode: {errorCode}',
    'Remove' => 'Fjern',
    'Retry' => 'Prøv igen',
    'Size not available' => 'Størrelse ikke tilgængelig',
    'Undo' => 'Undo',
    'Upload' => 'Upload',
    'Upload cancelled' => 'Upload annulleret',
    'Upload complete' => 'Upload komplet',
    'Uploading' => 'Uploading',
    'Waiting for size' => 'Venter på størrelse',
    'tap to cancel' => 'tryk for at annullere',
    'tap to retry' => 'tryk for at prøve igen',
    'tap to undo' => 'tryk for at fortryde',
];
