<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Avbryte',
    'Browse' => 'Bla',
    'Cancel' => 'Avbryt',
    'Drag & Drop your files or ' => 'Dra og slipp filene dine eller',
    'Error during load' => 'Feil under belastning',
    'Error during remove' => 'Feil under fjerning',
    'Error during revert' => 'Feil under tilbakestilling',
    'Error during revert.' => 'Feil under tilbakestilling.',
    'Error during upload' => 'Feil under opplasting',
    'Error during upload.' => 'Feil under opplasting.',
    'Field contains invalid files' => 'Feltet inneholder ugyldige filer',
    'Loading' => 'Laster',
    'Please, contact your administrator. Error code: {errorCode}' => 'Kontakt administratoren din. Feilkode: {errorCode}',
    'Remove' => 'Ta vekk',
    'Retry' => 'Prøv på nytt',
    'Size not available' => 'Størrelse ikke tilgjengelig',
    'Undo' => 'Angre',
    'Upload' => 'Laste opp',
    'Upload cancelled' => 'Last ned kansellert',
    'Upload complete' => 'Last opp fullført',
    'Uploading' => 'Laster opp',
    'Waiting for size' => 'Venter på størrelse',
    'tap to cancel' => 'trykk for å avbryte',
    'tap to retry' => 'trykk for å prøve på nytt',
    'tap to undo' => 'trykk for å angre',
];
