<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abort',
    'Browse' => 'Browse',
    'Cancel' => 'Annuler',
    'Drag & Drop your files or ' => 'Glissez et déposez vos fichiers ou ',
    'Error during load' => 'Erreur pendant le chargement',
    'Error during remove' => 'Erreur lors de la suppression',
    'Error during revert' => 'Erreur lors du retour',
    'Error during revert.' => 'Erreur lors du retour.',
    'Error during upload' => 'Erreur lors du téléchargement',
    'Error during upload.' => 'Erreur lors du téléchargement.',
    'Field contains invalid files' => 'Le champ contient des fichiers invalides',
    'Loading' => 'Loading',
    'Please, contact your administrator. Error code: {errorCode}' => 'Veuillez contacter votre administrateur. Code d\'erreur: {errorCode}',
    'Remove' => 'Remove',
    'Retry' => 'Réessayer',
    'Size not available' => 'Taille non disponible',
    'Undo' => 'Annuler',
    'Upload' => 'Upload',
    'Upload cancelled' => 'Téléchargement annulé',
    'Upload complete' => 'Upload complete',
    'Uploading' => 'Uploading',
    'Waiting for size' => 'En attente de taille',
    'tap to cancel' => 'appuyez pour annuler',
    'tap to retry' => 'tap to retry',
    'tap to undo' => 'tap to undo',
];
