<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Batalkan',
    'Browse' => 'Jelajahi',
    'Cancel' => 'Batalkan',
    'Drag & Drop your files or ' => 'Seret & Jatuhkan file Anda atau ',
    'Error during load' => 'Kesalahan saat memuat',
    'Error during remove' => 'Kesalahan saat menghapus',
    'Error during revert' => 'Kesalahan saat mengembalikan',
    'Error during revert.' => 'Kesalahan saat kembali.',
    'Error during upload' => 'Kesalahan saat mengunggah',
    'Error during upload.' => 'Kesalahan saat mengunggah.',
    'Field contains invalid files' => 'Field berisi file yang tidak valid',
    'Loading' => 'Memuat',
    'Please, contact your administrator. Error code: {errorCode}' => 'Silakan, hubungi administrator Anda. Kode kesalahan: {errorCode}',
    'Remove' => 'Hapus',
    'Retry' => 'Coba lagi',
    'Size not available' => 'Ukuran tidak tersedia',
    'Undo' => 'Undo',
    'Upload' => 'Unggah',
    'Upload cancelled' => 'Upload dibatalkan',
    'Upload complete' => 'Upload selesai',
    'Uploading' => 'Mengunggah',
    'Waiting for size' => 'Menunggu ukuran',
    'tap to cancel' => 'ketuk untuk membatalkan',
    'tap to retry' => 'ketuk untuk mencoba lagi',
    'tap to undo' => 'ketuk untuk membatalkan',
];
