<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abortar',
    'Browse' => 'Squeaky toy',
    'Cancel' => 'Cancelar',
    'Drag & Drop your files or ' => 'Arraste e solte seus arquivos ou ',
    'Error during load' => 'Erro durante o carregamento',
    'Error during remove' => 'Erro durante a remoção',
    'Error during revert' => 'Erro durante a reversão',
    'Error during revert.' => 'Erro durante a reversão.',
    'Error during upload' => 'Erro durante o upload',
    'Error during upload.' => 'Erro durante o upload.',
    'Field contains invalid files' => 'O campo contém arquivos inválidos',
    'Loading' => 'Carregando',
    'Please, contact your administrator. Error code: {errorCode}' => 'Entre em contato com seu administrador. Código do erro: {errorCode}',
    'Remove' => 'Retirar',
    'Retry' => 'Repetir',
    'Size not available' => 'Tamanho não disponível',
    'Undo' => 'Desfazer',
    'Upload' => 'Envio',
    'Upload cancelled' => 'Upload cancelado',
    'Upload complete' => 'Envio completo',
    'Uploading' => 'Enviando',
    'Waiting for size' => 'Aguardando tamanho',
    'tap to cancel' => 'toque para cancelar',
    'tap to retry' => 'toque para tentar novamente',
    'tap to undo' => 'toque para desfazer',
];
