<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abort',
    'Browse' => 'Sfoglia',
    'Cancel' => 'Annulla',
    'Drag & Drop your files or ' => 'Trascina e rilascia i tuoi file o ',
    'Error during load' => 'Errore durante il caricamento',
    'Error during remove' => 'Errore durante la rimozione',
    'Error during revert' => 'Errore durante il ripristino',
    'Error during revert.' => 'Errore durante il ripristino.',
    'Error during upload' => 'Errore durante il caricamento',
    'Error during upload.' => 'Errore durante il caricamento.',
    'Field contains invalid files' => 'Field contiene file non validi',
    'Loading' => 'Loading',
    'Please, contact your administrator. Error code: {errorCode}' => 'Per favore, contatta il tuo amministratore. Codice errore: {errorCode}',
    'Remove' => 'Rimuovi',
    'Retry' => 'Riprova',
    'Size not available' => 'Dimensione non disponibile',
    'Undo' => 'Annulla',
    'Upload' => 'Upload',
    'Upload cancelled' => 'Upload cancellato',
    'Upload complete' => 'Upload complete',
    'Uploading' => 'Uploading',
    'Waiting for size' => 'In attesa di dimensioni',
    'tap to cancel' => 'tocca per annullare',
    'tap to retry' => 'tap to retry',
    'tap to undo' => 'tocca per annullare',
];
