<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => '中止',
    'Browse' => '瀏覽',
    'Cancel' => '取消',
    'Drag & Drop your files or ' => '拖放文件或',
    'Error during load' => '加載期間錯誤',
    'Error during remove' => '移除期間發生錯誤',
    'Error during revert' => '還原期間發生錯誤',
    'Error during revert.' => '還原期間出錯。',
    'Error during upload' => '上載時發生錯誤',
    'Error during upload.' => '上載時發生錯誤。',
    'Field contains invalid files' => '字段包含無效文件',
    'Loading' => '載入中',
    'Please, contact your administrator. Error code: {errorCode}' => '請與您的管理員聯繫。 錯誤代碼：{errorCode}',
    'Remove' => '去掉',
    'Retry' => '重試',
    'Size not available' => '大小不可用',
    'Undo' => '撤消',
    'Upload' => '上載',
    'Upload cancelled' => '上載已取消',
    'Upload complete' => '上傳完成',
    'Uploading' => '上載中',
    'Waiting for size' => '等待大小',
    'tap to cancel' => '點擊取消',
    'tap to retry' => '點擊重試',
    'tap to undo' => '點擊撤消',
];
