<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Anulować',
    'Browse' => 'Przeglądaj',
    'Cancel' => 'Anuluj',
    'Drag & Drop your files or ' => 'Przeciągnij i upuść swoje pliki lub',
    'Error during load' => 'Błąd podczas ładowania',
    'Error during remove' => 'Błąd podczas usuwania',
    'Error during revert' => 'Błąd podczas przywracania',
    'Error during revert.' => 'Błąd podczas przywracania.',
    'Error during upload' => 'Błąd podczas przesyłania',
    'Error during upload.' => 'Błąd podczas przesyłania.',
    'Field contains invalid files' => 'Pole zawiera nieprawidłowe pliki',
    'Loading' => 'Ładowanie',
    'Please, contact your administrator. Error code: {errorCode}' => 'Proszę skontaktować się z administratorem. Kod błędu: {errorCode}',
    'Remove' => 'Usunąć',
    'Retry' => 'Spróbować ponownie',
    'Size not available' => 'Rozmiar niedostępny',
    'Undo' => 'Cofnij',
    'Upload' => 'Przekazać plik',
    'Upload cancelled' => 'Przesyłanie anulowane',
    'Upload complete' => 'Wgrywanie zakończone',
    'Uploading' => 'Przesyłanie',
    'Waiting for size' => 'Czekam na rozmiar',
    'tap to cancel' => 'dotknij, aby anulować',
    'tap to retry' => 'Dotknij, aby powtórzyć',
    'tap to undo' => 'dotknij, aby cofnąć',
];
