<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => '中止',
    'Browse' => '参照',
    'Cancel' => 'キャンセル',
    'Drag & Drop your files or ' => 'ファイルをドラッグアンドドロップするか、',
    'Error during load' => 'ロード中のエラー',
    'Error during remove' => '削除中のエラー',
    'Error during revert' => '復帰中のエラー',
    'Error during revert.' => '復帰中のエラー。',
    'Error during upload' => 'アップロード中のエラー',
    'Error during upload.' => 'アップロード中のエラー。',
    'Field contains invalid files' => 'フィールドに無効なファイルが含まれています',
    'Loading' => 'ロード中',
    'Please, contact your administrator. Error code: {errorCode}' => '管理者に連絡してください。 エラーコード：{errorCode}',
    'Remove' => '削除',
    'Retry' => '再試行',
    'Size not available' => 'サイズがありません',
    'Undo' => '元に戻す',
    'Upload' => 'アップロード',
    'Upload cancelled' => 'アップロードがキャンセルされました',
    'Upload complete' => 'アップロード完了',
    'Uploading' => 'アップロード',
    'Waiting for size' => 'サイズ待ち',
    'tap to cancel' => 'キャンセルするにはタップしてください',
    'tap to retry' => '再試行するにはタップしてください',
    'tap to undo' => '元に戻すにはタップしてください',
];
