<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'İptal',
    'Browse' => 'Araştır',
    'Cancel' => 'İptal etmek',
    'Drag & Drop your files or ' => 'Dosyalarınızı Sürükleyip Bırakın veya',
    'Error during load' => 'Yükleme sırasında hata',
    'Error during remove' => 'Kaldırma sırasında hata',
    'Error during revert' => 'Geri alma sırasında hata',
    'Error during revert.' => 'Geri alma sırasında hata.',
    'Error during upload' => 'Yükleme sırasında hata',
    'Error during upload.' => 'Yükleme sırasında hata.',
    'Field contains invalid files' => 'Alan geçersiz dosyalar içeriyor',
    'Loading' => 'Yükleniyor',
    'Please, contact your administrator. Error code: {errorCode}' => 'Lütfen yöneticinize başvurun. Hata kodu: {errorCode}',
    'Remove' => 'Kaldırmak',
    'Retry' => 'Yeniden Dene',
    'Size not available' => 'Boyut mevcut değil',
    'Undo' => 'Geri alma',
    'Upload' => 'Yükleme',
    'Upload cancelled' => 'Yükleme iptal edildi',
    'Upload complete' => 'Yükleme tamamlandı',
    'Uploading' => 'Yükleme',
    'Waiting for size' => 'Boyut bekleniyor',
    'tap to cancel' => 'iptal etmek için hafifçe vurun',
    'tap to retry' => 'Tekrar denemek için tıkla',
    'tap to undo' => 'geri almak için hafifçe vurun',
];
